erDiagram
     stocks ||--o{ products : contains
     events ||--o{ stocks : has
     stocks ||--o{ sales : has
     productCategories ||--o{ products : has
     tags ||--o{ products : has

     events {
         int eventId PK
         string name
         int timestamp
         string description
         string note
         int active
     }

     productCategories {
         int productCategoryId PK
         string name
         string description
         string imageUrl
         string note
         int active
     }

     products {
         int productId PK
         int productCategoryId FK
         string name
         int timestamp
         float purchasePrice
         string description
         string imageUrl
         string manualUrl
         string note
         int active
     }

     stocks {
         int stockId PK
         int eventId FK
         int productId FK
         int initialNumberInStock
         int currentNumberInStock
         float salePrice
         string note
         int favorite
         int active
     }

     sales {
         int saleId PK
         int stockId FK
         int numberItemsSold
         int timestamp
         string note
     }

     tags {
         int tagId PK
         int productId FK
         string name
         string value
         string note
         int active
     }