erDiagram
     stocks ||--o{ products : contains
     events ||--o{ stocks : has
     stocks ||--o{ sales : has
     productCategories ||--o{ products : has
     tags ||--o{ products : has
     carts ||--o{ sales : contains
     productRelations ||--|| products : has

     events {
         int eventId PK
         string uuid
         string name
         int timestamp
         string description
         string image
         string note
         int active
     }

     productCategories {
         int productCategoryId PK
         string uuid
         string name
         string description
         string image
         string note
         int active
     }

     products {
         int productId PK
         string uuid
         int productCategoryId FK
         string name
         int timestamp
         float purchasePrice
         string description
         string image
         string url
         string manualUrl
         string note
         int active
     }


     productRelations {
         int productRelationId PK
         string uuid
         int fromProductId FK
         int toProductId FK
         string fromDescription
         string toDescription
         string note
         int active
     }

     stocks {
         int stockId PK
         string uuid
         int eventId FK
         int productId FK
         int initialNumberInStock
         int currentNumberInStock
         float salePrice
         string note
         int favorite
         int active
     }

     carts {
         int cartId PK
         string uuid
         string name
         int timestamp
         string note
         int active
     }
     
     sales {
         int saleId PK
         string uuid
         int cartId FK
         int stockId FK
         int numberItemsSold
         int timestamp
         string note
     }

     tags {
         int tagId PK
         string uuid
         int productId FK
         string name
         string value
         string note
         int active
     }

     config {
         int configId PK
         string uuid
         string key
         string value
         string note
         int active
     }
